// Code generated by go-asmgen. DO NOT EDIT.

//go:build s390x

#include "textflag.h"

TEXT ·xor16(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R1
	MOVD b+8(FP), R2
	MOVD out+16(FP), R3
	VL (R1), V0
	VL (R2), V1
	VX V0, V1, V2
	VST V2, (R3)
	RET

TEXT ·eq16(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R1
	MOVD b+8(FP), R2
	MOVD out+16(FP), R3
	VL (R1), V0
	VL (R2), V1
	VCEQB V0, V1, V2
	VST V2, (R3)
	RET

