package simd

//go:generate go run gen.go

// xor16 computes out = a XOR b over 16 bytes (one 128-bit vector register) using
// the s390x vector facility (VL / VX / VST), implemented in simd_s390x.s
// generated by go-asmgen.
func xor16(a, b, out *[16]byte)

// eq16 sets out[i] = 0xFF where a[i]==b[i] and 0x00 otherwise, over 16 bytes,
// using the s390x vector facility (VL / VCEQB / VST), implemented in
// simd_s390x.s generated by go-asmgen.
func eq16(a, b, out *[16]byte)
