// Code generated by go-asmgen. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

TEXT ·addI32x4(SB), NOSPLIT, $0-24
	MOVQ a+0(FP), AX
	MOVQ b+8(FP), BX
	MOVQ out+16(FP), CX
	MOVOU (AX), X0
	MOVOU (BX), X1
	PADDL X1, X0
	MOVOU X0, (CX)
	RET

