package simd

//go:generate go run gen.go

// addI32x4 computes out = a + b element-wise over four int32 lanes using SSE2
// (MOVOU / PADDL), implemented in simd_amd64.s generated by go-asmgen.
//
// go-asmgen lays out the ABI0 frame (three pointer arguments) and loads them;
// the vector body — packed load, packed add, packed store — is emitted through
// the Raw escape hatch, exactly as scalar arithmetic is. asmdecl validates the
// pointer loads; the runtime test validates the vector computation.
func addI32x4(a, b, out *[4]int32)
