// Code generated by go-asmgen. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

TEXT ·addI32x4(SB), NOSPLIT, $0-24
	MOVQ a+0(FP), AX
	MOVQ b+8(FP), BX
	MOVQ out+16(FP), CX
	MOVOU (AX), X0
	MOVOU (BX), X1
	PADDL X1, X0
	MOVOU X0, (CX)
	RET

TEXT ·addI32x8(SB), NOSPLIT, $0-24
	MOVQ a+0(FP), AX
	MOVQ b+8(FP), BX
	MOVQ out+16(FP), CX
	VMOVDQU (AX), Y0
	VMOVDQU (BX), Y1
	VPADDD Y1, Y0, Y2
	VMOVDQU Y2, (CX)
	RET

TEXT ·hasAVX2(SB), NOSPLIT, $0-1
	MOVB $0, ret+0(FP)
	XORL AX, AX
	CPUID
	CMPL AX, $7
	JL hasAVX2_unsupported
	MOVL $1, AX
	CPUID
	ANDL $0x18000000, CX // AVX and OSXSAVE
	CMPL CX, $0x18000000
	JNE hasAVX2_unsupported
	XORL CX, CX
	XGETBV
	ANDL $6, AX // XMM and YMM state enabled in XCR0
	CMPL AX, $6
	JNE hasAVX2_unsupported
	MOVL $7, AX
	XORL CX, CX
	CPUID
	TESTL $0x20, BX // AVX2
	JZ hasAVX2_unsupported
	MOVB $1, ret+0(FP)
hasAVX2_unsupported:
	RET

