package simd

//go:generate go run gen.go

// addI32x4 adds four int32 lanes with SSE2 (MOVOU / PADDL); addI32x8 adds eight
// with AVX2 (VMOVDQU / VPADDD, 256-bit Y registers). Both are implemented in
// simd_amd64.s generated by go-asmgen: go-asmgen lays out the ABI0 frame
// (pointer args) and the vector body is emitted through Raw.
func addI32x4(a, b, out *[4]int32)
func addI32x8(a, b, out *[8]int32)

// hasAVX2 reports whether the processor AND the operating system support AVX2.
// It is generated by amd64.FeatureProbe, not hand-written: the OS half (XGETBV
// over XCR0) is the part a hand-rolled probe forgets, and forgetting it means
// the upper 128 bits of every Y register are lost at the next context switch.
//
// addI32x8 must not be called when this is false.
func hasAVX2() bool
