// Code generated by go-asmgen. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

TEXT ·sumI64(SB), NOSPLIT, $0-32
	MOVQ s_base+0(FP), AX
	MOVQ s_len+8(FP), BX
	MOVQ $0, CX
loop:
	TESTQ BX, BX
	JZ done
	MOVQ (AX), DX
	ADDQ DX, CX
	ADDQ $8, AX
	DECQ BX
	JMP loop
done:
	MOVQ CX, ret+24(FP)
	RET

