// Code generated by go-asmgen. DO NOT EDIT.

//go:build riscv64

#include "textflag.h"

TEXT ·addInt64(SB), NOSPLIT, $0-24
	MOV a+0(FP), X5
	MOV b+8(FP), X6
	ADD X6, X5, X7
	MOV X7, ret+16(FP)
	RET

TEXT ·addInt32(SB), NOSPLIT, $0-12
	MOVW a+0(FP), X5
	MOVW b+4(FP), X6
	ADDW X6, X5, X7
	MOVW X7, ret+8(FP)
	RET

TEXT ·widenInt8(SB), NOSPLIT, $0-16
	MOVB a+0(FP), X5
	MOV X5, ret+8(FP)
	RET

TEXT ·widenUint8(SB), NOSPLIT, $0-16
	MOVBU a+0(FP), X5
	MOV X5, ret+8(FP)
	RET

TEXT ·addFloat64(SB), NOSPLIT, $0-24
	MOVD a+0(FP), F0
	MOVD b+8(FP), F1
	FADDD F1, F0, F2
	MOVD F2, ret+16(FP)
	RET

TEXT ·addFloat32(SB), NOSPLIT, $0-12
	MOVF a+0(FP), F0
	MOVF b+4(FP), F1
	FADDS F1, F0, F2
	MOVF F2, ret+8(FP)
	RET

