package types

//go:generate go run gen.go

// These functions are implemented in types_riscv64.s, generated by go-asmgen.
// They exercise the riscv64 move surface — MOV (8-byte int, not MOVD),
// MOVB/MOVBU, MOVW, and the MOVF/MOVD float moves — validated by `go vet`
// asmdecl and the runtime tests (run under qemu-user in CI).

func addInt64(a, b int64) int64       // MOV   load / ADD  / MOV   store
func addInt32(a, b int32) int32       // MOVW  load / ADDW / MOVW  store
func widenInt8(a int8) int64          // MOVB  (sign-extend) / MOV store
func widenUint8(a uint8) uint64       // MOVBU (zero-extend) / MOV store
func addFloat64(a, b float64) float64 // MOVD  / FADDD / MOVD
func addFloat32(a, b float32) float32 // MOVF  / FADDS / MOVF
