package simd

//go:generate go run gen.go

// xor16 computes out = a ^ b over a 16-byte vector using the POWER VSX/AltiVec
// extension (LXVD2X / VXOR / STXVD2X), implemented in simd_ppc64le.s generated
// by go-asmgen.
func xor16(a, b, out *[16]byte)

// eq16 sets each byte of out to 0xFF where a and b are equal and 0x00 otherwise,
// over a 16-byte vector, using VCMPEQUB (LXVD2X / VCMPEQUB / STXVD2X), also
// generated by go-asmgen.
func eq16(a, b, out *[16]byte)

// Two-lane float64 kernels built from the VSX encoders (ppc64.Builder.XVADDDP
// and friends), each out[i] = a[i] OP b[i]; vsqrt2 is out[i] = sqrt(b[i]) and
// vfma2 is out[i] = a[i]*b[i] + c[i] with one rounding.
func vadd2(a, b, out *[2]float64)
func vsub2(a, b, out *[2]float64)
func vmul2(a, b, out *[2]float64)
func vdiv2(a, b, out *[2]float64)
func vmax2(a, b, out *[2]float64)
func vmin2(a, b, out *[2]float64)
func vsqrt2(a, b, out *[2]float64)
func vfma2(a, b, c, out *[2]float64)
