package simd

//go:generate go run gen.go

// xor16 computes out = a ^ b over a 16-byte vector using the POWER VSX/AltiVec
// extension (LXVD2X / VXOR / STXVD2X), implemented in simd_ppc64le.s generated
// by go-asmgen.
func xor16(a, b, out *[16]byte)

// eq16 sets each byte of out to 0xFF where a and b are equal and 0x00 otherwise,
// over a 16-byte vector, using VCMPEQUB (LXVD2X / VCMPEQUB / STXVD2X), also
// generated by go-asmgen.
func eq16(a, b, out *[16]byte)
