// Code generated by go-asmgen. DO NOT EDIT.

//go:build ppc64le

#include "textflag.h"

TEXT ·xor16(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R3
	MOVD b+8(FP), R4
	MOVD out+16(FP), R5
	LXVD2X (R3)(R0), VS32
	LXVD2X (R4)(R0), VS33
	VXOR V0, V1, V2
	STXVD2X VS34, (R5)(R0)
	RET

TEXT ·eq16(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R3
	MOVD b+8(FP), R4
	MOVD out+16(FP), R5
	LXVD2X (R3)(R0), VS32
	LXVD2X (R4)(R0), VS33
	VCMPEQUB V0, V1, V2
	STXVD2X VS34, (R5)(R0)
	RET

