package emit

import (
	"strings"
	"testing"
)

func TestFileData(t *testing.T) {
	fl := NewFile("amd64")
	sym := fl.Data("weights", []byte{0x10, 0x0f})
	if sym != "weights<>" {
		t.Errorf("Data returned %q want weights<>", sym)
	}
	got := fl.String()
	for _, want := range []string{
		"DATA weights<>+0(SB)/1, $0x10\n",
		"DATA weights<>+1(SB)/1, $0x0f\n",
		"GLOBL weights<>(SB), RODATA|NOPTR, $2\n",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("File.Data output missing %q\nfull:\n%s", want, got)
		}
	}
}

func TestFunctionStringWithFlags(t *testing.T) {
	fn := NewFunction("add", "NOSPLIT", 0, 24)
	fn.Insn("MOVD a+%d(FP), R0", 0)
	fn.Insn("RET")

	want := "TEXT ·add(SB), NOSPLIT, $0-24\n" +
		"\tMOVD a+0(FP), R0\n" +
		"\tRET\n"
	if got := fn.String(); got != want {
		t.Errorf("Function.String() with flags:\ngot:\n%q\nwant:\n%q", got, want)
	}
}

func TestFunctionLabel(t *testing.T) {
	fn := NewFunction("f", "NOSPLIT", 0, 8)
	fn.Label("loop")
	fn.Insn("RET")
	want := "TEXT ·f(SB), NOSPLIT, $0-8\n" +
		"loop:\n" + // column 0, no leading tab
		"\tRET\n"
	if got := fn.String(); got != want {
		t.Errorf("Function.Label:\ngot:\n%q\nwant:\n%q", got, want)
	}
}

func TestFunctionStringNoFlags(t *testing.T) {
	fn := NewFunction("noop", "", 16, 0)
	want := "TEXT ·noop(SB), $16-0\n"
	if got := fn.String(); got != want {
		t.Errorf("Function.String() no flags:\ngot:\n%q\nwant:\n%q", got, want)
	}
}

func TestFileStringWithBuildConstraint(t *testing.T) {
	fn1 := NewFunction("a", "NOSPLIT", 0, 8)
	fn1.Insn("RET")
	fn2 := NewFunction("b", "NOSPLIT", 0, 8)
	fn2.Insn("RET")

	fl := NewFile("arm64")
	fl.Add(fn1)
	fl.Add(fn2)

	want := "// Code generated by go-asmgen. DO NOT EDIT.\n\n" +
		"//go:build arm64\n\n" +
		"#include \"textflag.h\"\n\n" +
		"TEXT ·a(SB), NOSPLIT, $0-8\n\tRET\n\n" +
		"TEXT ·b(SB), NOSPLIT, $0-8\n\tRET\n\n"
	if got := fl.String(); got != want {
		t.Errorf("File.String() with build:\ngot:\n%q\nwant:\n%q", got, want)
	}
}

func TestFileStringNoBuildConstraint(t *testing.T) {
	fl := NewFile("")
	want := "// Code generated by go-asmgen. DO NOT EDIT.\n\n" +
		"#include \"textflag.h\"\n\n"
	if got := fl.String(); got != want {
		t.Errorf("File.String() no build:\ngot:\n%q\nwant:\n%q", got, want)
	}
}
