// Package emit builds Plan 9 assembly text. It is deliberately dumb: it knows
// how to write well-formed Plan 9 .s lines, nothing about any specific ISA. The
// architecture packages (arm64, riscv64, loong64) drive it via their Builders,
// and a File collects the resulting functions into a complete .s source.
package emit

import (
	"fmt"
	"strings"
)

// Function accumulates the lines of a single Plan 9 TEXT block.
type Function struct {
	name      string
	flags     string // e.g. "NOSPLIT"
	frameSize int    // local frame, $<frameSize>
	argsSize  int    // argument+return area size, -<argsSize>
	body      []string
}

// NewFunction starts a TEXT block. argsSize is the total size in bytes of the
// argument+return region (ABI0); frameSize is the local stack frame.
func NewFunction(name, flags string, frameSize, argsSize int) *Function {
	return &Function{
		name:      name,
		flags:     flags,
		frameSize: frameSize,
		argsSize:  argsSize,
	}
}

// Insn appends a raw instruction line (already in Plan 9 syntax).
func (f *Function) Insn(format string, args ...any) {
	f.body = append(f.body, "\t"+fmt.Sprintf(format, args...))
}

// Label appends a branch-target definition, written at column 0 (no
// indentation) like hand-written assembly.
func (f *Function) Label(name string) {
	f.body = append(f.body, name+":")
}

// String renders the complete TEXT block.
func (f *Function) String() string {
	var b strings.Builder
	// ·name(SB) refers to the current package symbol.
	header := fmt.Sprintf("TEXT ·%s(SB)", f.name)
	if f.flags != "" {
		header += ", " + f.flags
	}
	header += fmt.Sprintf(", $%d-%d", f.frameSize, f.argsSize)
	b.WriteString(header + "\n")
	for _, line := range f.body {
		b.WriteString(line + "\n")
	}
	return b.String()
}

// File assembles one or more functions into a complete .s file.
type File struct {
	build string // build constraint, e.g. "arm64"
	funcs []*Function
	datas []dataSym
}

type dataSym struct {
	name  string
	bytes []byte
}

func NewFile(buildArch string) *File { return &File{build: buildArch} }

func (fl *File) Add(fn *Function) { fl.funcs = append(fl.funcs, fn) }

// Data declares a file-local, read-only constant table (the `DATA`/`GLOBL`
// directives) — the kind of byte table SIMD kernels load (a weight vector, a
// shuffle mask). It returns the symbol to address in instructions, e.g.
//
//	sym := f.Data("weights", []byte{16, 15, 14, 13})
//	b.Raw("MOVOU %s+0(SB), X0", sym)   // sym is "weights<>"
//
// The bytes are copied. RODATA|NOPTR mark the symbol read-only and pointer-free.
func (fl *File) Data(name string, b []byte) string {
	fl.datas = append(fl.datas, dataSym{name: name, bytes: append([]byte(nil), b...)})
	return name + "<>"
}

func (fl *File) String() string {
	var b strings.Builder
	b.WriteString("// Code generated by go-asmgen. DO NOT EDIT.\n\n")
	if fl.build != "" {
		b.WriteString("//go:build " + fl.build + "\n\n")
	}
	b.WriteString("#include \"textflag.h\"\n\n")
	for _, fn := range fl.funcs {
		b.WriteString(fn.String())
		b.WriteString("\n")
	}
	for _, d := range fl.datas {
		// One byte per DATA directive: simple and width-agnostic.
		for i, by := range d.bytes {
			fmt.Fprintf(&b, "DATA %s<>+%d(SB)/1, $0x%02x\n", d.name, i, by)
		}
		fmt.Fprintf(&b, "GLOBL %s<>(SB), RODATA|NOPTR, $%d\n\n", d.name, len(d.bytes))
	}
	return b.String()
}
