package simd

//go:generate go run gen.go

// addI32x4 computes out = a + b element-wise over four int32 lanes using NEON
// (VLD1 / VADD.S4 / VST1), implemented in simd_arm64.s generated by go-asmgen.
//
// go-asmgen lays out the ABI0 frame (three pointer arguments) and loads them;
// the vector body is emitted through the Raw escape hatch. asmdecl validates the
// pointer loads; the runtime test validates the vector computation.
func addI32x4(a, b, out *[4]int32)
