// Code generated by go-asmgen. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

TEXT ·sumI64x3(SB), NOSPLIT, $0-32
	MOVQ v_0+0(FP), AX
	MOVQ v_1+8(FP), BX
	MOVQ v_2+16(FP), CX
	ADDQ BX, AX
	ADDQ CX, AX
	MOVQ AX, ret+24(FP)
	RET

