// Code generated by go-asmgen. DO NOT EDIT.

//go:build arm64

#include "textflag.h"

TEXT ·sumI64x3(SB), NOSPLIT, $0-32
	MOVD v_0+0(FP), R0
	MOVD v_1+8(FP), R1
	MOVD v_2+16(FP), R2
	ADD R1, R0, R0
	ADD R2, R0, R0
	MOVD R0, ret+24(FP)
	RET

