package array

//go:generate go run gen.go

// sumI64x3 returns v[0]+v[1]+v[2] for a fixed-size array passed BY VALUE.
// Implemented in array_arm64.s, generated by go-asmgen: each element is
// addressed as v_0/v_1/v_2 and loaded with an ordinary MOVD.
func sumI64x3(v [3]int64) int64
