// Package emit builds Plan 9 assembly text. It is deliberately dumb: it knows
// how to write well-formed Plan 9 .s lines, nothing about any specific ISA.
// Architecture packages (arm64, later riscv64/loong64) drive it.
package emit

import (
	"fmt"
	"strings"
)

// Function accumulates the lines of a single Plan 9 TEXT block.
type Function struct {
	name      string
	flags     string // e.g. "NOSPLIT"
	frameSize int    // local frame, $<frameSize>
	argsSize  int    // argument+return area size, -<argsSize>
	body      []string
}

// NewFunction starts a TEXT block. argsSize is the total size in bytes of the
// argument+return region (ABI0); frameSize is the local stack frame.
func NewFunction(name, flags string, frameSize, argsSize int) *Function {
	return &Function{
		name:      name,
		flags:     flags,
		frameSize: frameSize,
		argsSize:  argsSize,
	}
}

// Insn appends a raw instruction line (already in Plan 9 syntax).
func (f *Function) Insn(format string, args ...any) {
	f.body = append(f.body, "\t"+fmt.Sprintf(format, args...))
}

// String renders the complete TEXT block.
func (f *Function) String() string {
	var b strings.Builder
	// ·name(SB) refers to the current package symbol.
	header := fmt.Sprintf("TEXT ·%s(SB)", f.name)
	if f.flags != "" {
		header += ", " + f.flags
	}
	header += fmt.Sprintf(", $%d-%d", f.frameSize, f.argsSize)
	b.WriteString(header + "\n")
	for _, line := range f.body {
		b.WriteString(line + "\n")
	}
	return b.String()
}

// File assembles one or more functions into a complete .s file.
type File struct {
	build string // build constraint, e.g. "arm64"
	funcs []*Function
}

func NewFile(buildArch string) *File { return &File{build: buildArch} }

func (fl *File) Add(fn *Function) { fl.funcs = append(fl.funcs, fn) }

func (fl *File) String() string {
	var b strings.Builder
	b.WriteString("// Code generated by go-asmgen. DO NOT EDIT.\n\n")
	if fl.build != "" {
		b.WriteString("//go:build " + fl.build + "\n\n")
	}
	b.WriteString("#include \"textflag.h\"\n\n")
	for _, fn := range fl.funcs {
		b.WriteString(fn.String())
		b.WriteString("\n")
	}
	return b.String()
}
