// Code generated by go-asmgen. DO NOT EDIT.

//go:build loong64

#include "textflag.h"

TEXT ·pairSum(SB), NOSPLIT, $0-24
	MOVV p_A+0(FP), R4
	MOVV p_B+8(FP), R5
	ADDV R5, R4, R6
	MOVV R6, ret+16(FP)
	RET

TEXT ·mixedN(SB), NOSPLIT, $0-24
	MOVV m_N+8(FP), R4
	MOVV R4, ret+16(FP)
	RET

TEXT ·sliceLen(SB), NOSPLIT, $0-32
	MOVV s_len+8(FP), R4
	MOVV R4, ret+24(FP)
	RET

TEXT ·sliceFirst(SB), NOSPLIT, $0-32
	MOVV s_base+0(FP), R4
	MOVV (R4), R5
	MOVV R5, ret+24(FP)
	RET

TEXT ·strLen(SB), NOSPLIT, $0-24
	MOVV x_len+8(FP), R4
	MOVV R4, ret+16(FP)
	RET

