package array

//go:generate go run gen.go

// sumI64x3 returns v[0]+v[1]+v[2] for a fixed-size array passed by value.
// Implemented in array_loong64.s, generated by go-asmgen.
func sumI64x3(v [3]int64) int64
