// Code generated by go-asmgen. DO NOT EDIT.

//go:build loong64

#include "textflag.h"

TEXT ·sumI64x3(SB), NOSPLIT, $0-32
	MOVV v_0+0(FP), R4
	MOVV v_1+8(FP), R5
	MOVV v_2+16(FP), R6
	ADDV R5, R4, R4
	ADDV R6, R4, R4
	MOVV R4, ret+24(FP)
	RET

