package loop

//go:generate go run gen.go

// sumI64 returns the sum of all elements of s. Implemented in loop_riscv64.s,
// generated by go-asmgen: slice base + length, then a real loop (labels +
// conditional branch via Raw) accumulating each element.
func sumI64(s []int64) int64
