// Code generated by go-asmgen. DO NOT EDIT.

//go:build riscv64

#include "textflag.h"

TEXT ·sumI64(SB), NOSPLIT, $0-32
	MOV s_base+0(FP), X5
	MOV s_len+8(FP), X6
	MOV $0, X7
loop:
	BEQZ X6, done
	MOV (X5), X8
	ADD X8, X7, X7
	ADD $8, X5, X5
	ADD $-1, X6, X6
	JMP loop
done:
	MOV X7, ret+24(FP)
	RET

