// Code generated by go-asmgen. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

TEXT ·addVec(SB), NOSPLIT, $0-16
	MOVQ in+0(FP), AX
	MOVQ out+8(FP), BX
	MOVOU (AX), X0
	MOVOU addend<>+0(SB), X1
	PADDL X1, X0
	MOVOU X0, (BX)
	RET

DATA addend<>+0(SB)/1, $0x0a
DATA addend<>+1(SB)/1, $0x00
DATA addend<>+2(SB)/1, $0x00
DATA addend<>+3(SB)/1, $0x00
DATA addend<>+4(SB)/1, $0x14
DATA addend<>+5(SB)/1, $0x00
DATA addend<>+6(SB)/1, $0x00
DATA addend<>+7(SB)/1, $0x00
DATA addend<>+8(SB)/1, $0x1e
DATA addend<>+9(SB)/1, $0x00
DATA addend<>+10(SB)/1, $0x00
DATA addend<>+11(SB)/1, $0x00
DATA addend<>+12(SB)/1, $0x28
DATA addend<>+13(SB)/1, $0x00
DATA addend<>+14(SB)/1, $0x00
DATA addend<>+15(SB)/1, $0x00
GLOBL addend<>(SB), RODATA|NOPTR, $16

