// Code generated by go-asmgen. DO NOT EDIT.

//go:build riscv64

#include "textflag.h"

TEXT ·addI32x4(SB), NOSPLIT, $0-24
	MOV a+0(FP), X5
	MOV b+8(FP), X6
	MOV out+16(FP), X7
	VSETVLI $4, E32, M1, TA, MA, X8
	VLE32V (X5), V0
	VLE32V (X6), V1
	VADDVV V0, V1, V2
	VSE32V V2, (X7)
	RET

