package simd

//go:generate go run gen.go

// addI32x4 computes out = a + b element-wise over four int32 lanes using the
// RISC-V Vector extension (RVV: VSETVLI / VLE32.V / VADD.VV / VSE32.V),
// implemented in simd_riscv64.s generated by go-asmgen.
func addI32x4(a, b, out *[4]int32)
