// Code generated by go-asmgen. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

TEXT ·addInt64(SB), NOSPLIT, $0-24
	MOVQ a+0(FP), AX
	MOVQ b+8(FP), BX
	ADDQ BX, AX
	MOVQ AX, ret+16(FP)
	RET

TEXT ·addInt32(SB), NOSPLIT, $0-12
	MOVLQSX a+0(FP), AX
	MOVLQSX b+4(FP), BX
	ADDL BX, AX
	MOVL AX, ret+8(FP)
	RET

TEXT ·widenInt8(SB), NOSPLIT, $0-16
	MOVBQSX a+0(FP), AX
	MOVQ AX, ret+8(FP)
	RET

TEXT ·widenUint8(SB), NOSPLIT, $0-16
	MOVBQZX a+0(FP), AX
	MOVQ AX, ret+8(FP)
	RET

TEXT ·addFloat64(SB), NOSPLIT, $0-24
	MOVSD a+0(FP), X0
	MOVSD b+8(FP), X1
	ADDSD X1, X0
	MOVSD X0, ret+16(FP)
	RET

TEXT ·addFloat32(SB), NOSPLIT, $0-12
	MOVSS a+0(FP), X0
	MOVSS b+4(FP), X1
	ADDSS X1, X0
	MOVSS X0, ret+8(FP)
	RET

