package types

//go:generate go run gen.go

// These functions are implemented in types_amd64.s, generated by go-asmgen.
// They exercise the amd64 move surface — MOVQ (8-byte int), the sign/zero-
// extending sub-word loads (MOVBQSX/MOVBQZX), MOVL, and the SSE scalar float
// moves (MOVSS/MOVSD) — validated by `go vet` asmdecl and the runtime tests
// (run natively; ubuntu-latest is an amd64 runner).

func addInt64(a, b int64) int64       // MOVQ    / ADDQ / MOVQ
func addInt32(a, b int32) int32       // MOVLQSX / ADDL / MOVL
func widenInt8(a int8) int64          // MOVBQSX (sign-extend) / MOVQ
func widenUint8(a uint8) uint64       // MOVBQZX (zero-extend) / MOVQ
func addFloat64(a, b float64) float64 // MOVSD   / ADDSD / MOVSD
func addFloat32(a, b float32) float32 // MOVSS   / ADDSS / MOVSS
