package simd

//go:generate go run gen.go

// addI32x4 adds four int32 lanes with LSX (VMOVQ / VADDW, 128-bit); addI32x8
// adds eight with LASX (XVMOVQ / XVADDW, 256-bit X registers). Both are
// implemented in simd_loong64.s generated by go-asmgen.
func addI32x4(a, b, out *[4]int32)
func addI32x8(a, b, out *[8]int32)

// fmaF64x4 / fmaF64x2 compute out[i] = a[i]*b[i] + c[i] with one rounding
// (xvfmadd.d / vfmadd.d through go-asmgen's encoders); bcastF64 fills out4
// with p[3] and out2 with p[1] (xvldrepl.d / vldrepl.d).
func fmaF64x4(a, b, c, out *[4]float64)
func fmaF64x2(a, b, c, out *[2]float64)
func bcastF64(p *[4]float64, out4 *[4]float64, out2 *[2]float64)
