// Code generated by go-asmgen. DO NOT EDIT.

//go:build loong64

#include "textflag.h"

TEXT ·addI32x4(SB), NOSPLIT, $0-24
	MOVV a+0(FP), R4
	MOVV b+8(FP), R5
	MOVV out+16(FP), R6
	VMOVQ (R4), V0
	VMOVQ (R5), V1
	VADDW V0, V1, V2
	VMOVQ V2, (R6)
	RET

