package simd

//go:generate go run gen.go

// addI32x4 computes out = a + b element-wise over four int32 lanes using the
// LoongArch SIMD extension (LSX: VMOVQ 128-bit load/store, VADDW word lanes),
// implemented in simd_loong64.s generated by go-asmgen.
func addI32x4(a, b, out *[4]int32)
