package simd

//go:generate go run gen.go

// addI32x4 adds four int32 lanes with LSX (VMOVQ / VADDW, 128-bit); addI32x8
// adds eight with LASX (XVMOVQ / XVADDW, 256-bit X registers). Both are
// implemented in simd_loong64.s generated by go-asmgen.
func addI32x4(a, b, out *[4]int32)
func addI32x8(a, b, out *[8]int32)
