package loop

//go:generate go run gen.go

// sumI64 returns the sum of all elements of s. Implemented in loop_arm64.s,
// generated by go-asmgen: it loads the slice base and length, then runs a real
// loop (labels + conditional branch emitted through Raw) accumulating each
// element. This shows go-asmgen composes for non-straight-line functions.
func sumI64(s []int64) int64
