// Code generated by go-asmgen. DO NOT EDIT.

//go:build arm64

#include "textflag.h"

TEXT ·sumI64(SB), NOSPLIT, $0-32
	MOVD s_base+0(FP), R0
	MOVD s_len+8(FP), R1
	MOVD $0, R2
	loop:
	CBZ R1, done
	MOVD (R0), R3
	ADD R3, R2, R2
	ADD $8, R0, R0
	SUB $1, R1, R1
	JMP loop
	done:
	MOVD R2, ret+24(FP)
	RET

