// Code generated by go-asmgen. DO NOT EDIT.

//go:build arm64

#include "textflag.h"

TEXT ·addInt32(SB), NOSPLIT, $0-12
	MOVW a+0(FP), R0
	MOVW b+4(FP), R1
	ADDW R1, R0, R2
	MOVW R2, ret+8(FP)
	RET

TEXT ·addUint32(SB), NOSPLIT, $0-12
	MOVWU a+0(FP), R0
	MOVWU b+4(FP), R1
	ADDW R1, R0, R2
	MOVW R2, ret+8(FP)
	RET

TEXT ·addInt16(SB), NOSPLIT, $0-10
	MOVH a+0(FP), R0
	MOVH b+2(FP), R1
	ADD R1, R0, R2
	MOVH R2, ret+8(FP)
	RET

TEXT ·addInt8(SB), NOSPLIT, $0-9
	MOVB a+0(FP), R0
	MOVB b+1(FP), R1
	ADD R1, R0, R2
	MOVB R2, ret+8(FP)
	RET

TEXT ·widenInt8(SB), NOSPLIT, $0-16
	MOVB a+0(FP), R0
	MOVD R0, ret+8(FP)
	RET

TEXT ·widenUint8(SB), NOSPLIT, $0-16
	MOVBU a+0(FP), R0
	MOVD R0, ret+8(FP)
	RET

TEXT ·addFloat64(SB), NOSPLIT, $0-24
	FMOVD a+0(FP), F0
	FMOVD b+8(FP), F1
	FADDD F1, F0, F2
	FMOVD F2, ret+16(FP)
	RET

TEXT ·addFloat32(SB), NOSPLIT, $0-12
	FMOVS a+0(FP), F0
	FMOVS b+4(FP), F1
	FADDS F1, F0, F2
	FMOVS F2, ret+8(FP)
	RET

