// Code generated by go-asmgen. DO NOT EDIT.

//go:build arm64

#include "textflag.h"

TEXT ·spillSum(SB), $16-24
	MOVD a+0(FP), R0
	MOVD R0, s0-8(SP)
	MOVD b+8(FP), R1
	MOVD R1, s1-16(SP)
	MOVD s0-8(SP), R2
	MOVD s1-16(SP), R3
	ADD R3, R2, R2
	MOVD R2, ret+16(FP)
	RET

