// Code generated by go-asmgen. DO NOT EDIT.

//go:build loong64

#include "textflag.h"

TEXT ·addInt64(SB), NOSPLIT, $0-24
	MOVV a+0(FP), R4
	MOVV b+8(FP), R5
	ADDV R5, R4, R6
	MOVV R6, ret+16(FP)
	RET

TEXT ·addInt32(SB), NOSPLIT, $0-12
	MOVW a+0(FP), R4
	MOVW b+4(FP), R5
	ADDV R5, R4, R6
	MOVW R6, ret+8(FP)
	RET

TEXT ·widenInt8(SB), NOSPLIT, $0-16
	MOVB a+0(FP), R4
	MOVV R4, ret+8(FP)
	RET

TEXT ·widenUint8(SB), NOSPLIT, $0-16
	MOVBU a+0(FP), R4
	MOVV R4, ret+8(FP)
	RET

TEXT ·addFloat64(SB), NOSPLIT, $0-24
	MOVD a+0(FP), F0
	MOVD b+8(FP), F1
	ADDD F1, F0, F2
	MOVD F2, ret+16(FP)
	RET

TEXT ·addFloat32(SB), NOSPLIT, $0-12
	MOVF a+0(FP), F0
	MOVF b+4(FP), F1
	ADDF F1, F0, F2
	MOVF F2, ret+8(FP)
	RET

