package types

//go:generate go run gen.go

// These functions are implemented in types_loong64.s, generated by go-asmgen.
// They exercise the loong64 move surface — MOVV (8-byte int), MOVB/MOVBU, MOVW,
// and the MOVF/MOVD float moves — validated by `go vet` asmdecl and the runtime
// tests (run under qemu-user in CI).

func addInt64(a, b int64) int64       // MOVV  load / ADDV / MOVV  store
func addInt32(a, b int32) int32       // MOVW  load / ADDV / MOVW  store
func widenInt8(a int8) int64          // MOVB  (sign-extend) / MOVV store
func widenUint8(a uint8) uint64       // MOVBU (zero-extend) / MOVV store
func addFloat64(a, b float64) float64 // MOVD  / ADDD / MOVD
func addFloat32(a, b float32) float32 // MOVF  / ADDF / MOVF
