// Code generated by go-asmgen. DO NOT EDIT.

//go:build riscv64

#include "textflag.h"

TEXT ·pairSum(SB), NOSPLIT, $0-24
	MOV p_A+0(FP), X5
	MOV p_B+8(FP), X6
	ADD X6, X5, X7
	MOV X7, ret+16(FP)
	RET

TEXT ·mixedN(SB), NOSPLIT, $0-24
	MOV m_N+8(FP), X5
	MOV X5, ret+16(FP)
	RET

TEXT ·sliceLen(SB), NOSPLIT, $0-32
	MOV s_len+8(FP), X5
	MOV X5, ret+24(FP)
	RET

TEXT ·sliceFirst(SB), NOSPLIT, $0-32
	MOV s_base+0(FP), X5
	MOV (X5), X6
	MOV X6, ret+24(FP)
	RET

TEXT ·strLen(SB), NOSPLIT, $0-24
	MOV x_len+8(FP), X5
	MOV X5, ret+16(FP)
	RET

