package aggregate

//go:generate go run gen.go

// Pair and Mixed are struct arguments passed by value under ABI0.
type (
	Pair  struct{ A, B int64 }
	Mixed struct {
		Flag int8
		N    int64
	}
)

// Implemented in aggregate_riscv64.s, generated by go-asmgen — struct / slice /
// string parameters addressed field-wise (name_field+offset(FP)).

func pairSum(p Pair) int64       // p_A + p_B
func mixedN(m Mixed) int64       // m_N (field after padding)
func sliceLen(s []int64) int     // s_len
func sliceFirst(s []int64) int64 // *(s_base)
func strLen(x string) int        // x_len
