// Code generated by go-asmgen. DO NOT EDIT.

//go:build arm64

#include "textflag.h"

TEXT ·pairSum(SB), NOSPLIT, $0-24
	MOVD p_A+0(FP), R0
	MOVD p_B+8(FP), R1
	ADD R1, R0, R2
	MOVD R2, ret+16(FP)
	RET

TEXT ·mixedN(SB), NOSPLIT, $0-24
	MOVD m_N+8(FP), R0
	MOVD R0, ret+16(FP)
	RET

TEXT ·sliceLen(SB), NOSPLIT, $0-32
	MOVD s_len+8(FP), R0
	MOVD R0, ret+24(FP)
	RET

TEXT ·sliceFirst(SB), NOSPLIT, $0-32
	MOVD s_base+0(FP), R0
	MOVD (R0), R1
	MOVD R1, ret+24(FP)
	RET

TEXT ·strLen(SB), NOSPLIT, $0-24
	MOVD x_len+8(FP), R0
	MOVD R0, ret+16(FP)
	RET

