// Code generated by go-asmgen. DO NOT EDIT.

//go:build riscv64

#include "textflag.h"

TEXT ·sumI64x3(SB), NOSPLIT, $0-32
	MOV v_0+0(FP), X5
	MOV v_1+8(FP), X6
	MOV v_2+16(FP), X7
	ADD X6, X5, X5
	ADD X7, X5, X5
	MOV X5, ret+24(FP)
	RET

