package aggregate

//go:generate go run gen.go

// Pair and Mixed are struct arguments passed by value under ABI0. Mixed has a
// sub-word field before an 8-byte field, so its second field is padded.
type (
	Pair  struct{ A, B int64 }
	Mixed struct {
		Flag int8
		N    int64
	}
)

// These functions are implemented in aggregate_amd64.s, generated by go-asmgen.
// They exercise aggregate (struct / slice / string) parameters on amd64: each
// field is addressed as name_field+offset(FP), validated by asmdecl and the
// runtime tests.

func pairSum(p Pair) int64       // p_A + p_B
func mixedN(m Mixed) int64       // m_N (field after padding)
func sliceLen(s []int64) int     // s_len
func sliceFirst(s []int64) int64 // *(s_base)
func strLen(x string) int        // x_len
