// Code generated by go-asmgen. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

TEXT ·pairSum(SB), NOSPLIT, $0-24
	MOVQ p_A+0(FP), AX
	MOVQ p_B+8(FP), BX
	ADDQ BX, AX
	MOVQ AX, ret+16(FP)
	RET

TEXT ·mixedN(SB), NOSPLIT, $0-24
	MOVQ m_N+8(FP), AX
	MOVQ AX, ret+16(FP)
	RET

TEXT ·sliceLen(SB), NOSPLIT, $0-32
	MOVQ s_len+8(FP), AX
	MOVQ AX, ret+24(FP)
	RET

TEXT ·sliceFirst(SB), NOSPLIT, $0-32
	MOVQ s_base+0(FP), AX
	MOVQ (AX), BX
	MOVQ BX, ret+24(FP)
	RET

TEXT ·strLen(SB), NOSPLIT, $0-24
	MOVQ x_len+8(FP), AX
	MOVQ AX, ret+16(FP)
	RET

